---
title: ReactForce
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:title"
tagline: React with jedi force
paginate: 1
baseurl: ''
sass:
  sass_dir: _sass
  style: :compressed
author:
  name: Bilal Nazir
  url: https://twitter.com/bilalnazir90
  email: bilal.nazirahmad@gmail.com
github: https://github.com/bilalfastian
version: 1.0.0
gems:
- jekyll-paginate
- jekyll-gist
